baseurl = "http://folospior.github.io"
title = "Folo"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "folospior"
  info = "Discord Bot Developer"
  description = "The personal website of folospior, also known as Folo or fo1o."
  keywords = "blog,developer,personal"
  avatarurl = "img/avatar.jpg"

  faviconSVG = "img/favicon.svg"

  since = 2023

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/folospior/"
[[params.social]]
  name = "Discord"
  icon = "fa fa-discord fa-2x"
  weight = 2
  url = "https://discordapp.com/users/808763186811633735"
[[params.social]]
    name = "Website Source"
    icon = "fa fa-globe fa-2x"
    weight = 3
    url = "source"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"